### ISSUE TITLE
New survivors need 4th Skill Upgrade

### ISSUE THREAD

**Issue by Nematocyst** [ThinkInvis/RoR2-ClassicItems#104] opened 2022-04-28 04:21 UTC
After the new DLC release, the two new survivors + the heretic need their fourth skill upgrade defined.  

That the Railgunner, Void Fiend and Heretic get their 4th upgrade when the Ancient Scepter is chosen

The Railgunner could use an upgrade for the Charging Attacks.  Either doubling the damage % or adding some effect like push back or healing. 

The Heretic could either use an upgrade for the Maelstrom attack like increasing the AoE or adding the hook mechanic to pull enemies in. An alternative could be upgrading the Shadowfade mobility skill.  Doubling or Tripling the duration could help a lot.  

The Void Fiend proves trickier as their two stage abilities present a challenge.  Perhaps reducing the cooldown of their charging abilities would help.

**Comment by ThinkInvis** [comment] 2022-04-28 13:45
Duplicate of #79.

**Closed as completed by ThinkInvis** 2022-04-28 13:45 UTC
Labels: duplicate
