### ISSUE TITLE
All interactables vanish

### ISSUE THREAD

**Issue by imakunee** [ThinkInvis/RoR2-ClassicItems#87] opened 2021-04-13 23:02 UTC
## Describe the Bug
There are no chests, shops, shrines, nor other interactables when using this mod. I wasn't confident that this might be a duplicate of #86 since everything seems to **_load_** fine on my end.

### To Reproduce
1. Just launch up an otherwise vanilla game with all the dependencies and wander around until you're confident there's nothing on the map.

### Expected Behavior
The game would run normally but with the additional items in the item pool.

### Console Log
https://pastebin.com/vxRdpwtt

Thank you very much for your work on your mods. I'm a huge fan of the item mods as they add just so much replayability to the game for me.

**Comment by StalwartTirith** [comment] 2021-04-14 14:51
Can confirm, the mod is completely broken and, while the game loads and enemies spawn, no interactables will spawn. This includes item drops on sacrifice; items won't drop no matter how many enemies you kill. Teleporters don't even spawn. 
Until this is fixed this is just completely broken.

**Comment by ThinkInvis** [comment] 2021-04-22 18:57
Almost certainly a duplicate of #86. See comment on said issue; feel free to reopen if it's still happening after I update.

**Closed as completed by ThinkInvis** 2021-04-22 18:57 UTC
Labels: duplicate
