### ISSUE TITLE
Huntress Ancient Scepter bug

### ISSUE THREAD

**Issue by SwankyMcSwankyPants** [ThinkInvis/RoR2-ClassicItems#51] opened 2020-08-25 03:35 UTC
When using AS you'll get the opposite upgrade for your current R ability. Ex. If you have Ballista equipped your upgrade will be arrow rain and vice versa

**Comment by ThinkInvis** [comment] 2020-08-25 18:47
Duplicate of https://github.com/ThinkInvis/RoR2-ClassicItems/issues/50.

**Closed as completed by ThinkInvis** 2020-08-25 18:47 UTC
Labels: duplicate
