### ISSUE TITLE
Items as a whole are broken

### ISSUE THREAD

**Issue by gubbr** [ThinkInvis/RoR2-ClassicItems#88] opened 2021-04-14 15:09 UTC
### Describe the Bug
When loading into RoR2 with ClassicItems and its dependencies, the items list in the logbook in the menu is blank, as shown in Additional Context. All other lists (monster, environment, etc.) are unaffected. When loading into the game, chests and other interactables are present, but when interacting with chests it shoots out the item but no item actually appears. I didn't test in multiplayer, but with the nature of the bug, I don't think anything would change.

~ After playing around with it for a bit trying to set the conditions again to reproduce the log, I noticed that booting up a singleplayer game would initially result in no chests or interactables spawning, like #87. If you start a game with the Sacrifice artifact enabled and then exit and start a game with it disabled, it results in chests spawning again, but with no items on purchase. The second time around, there was no item-shooting-out animation, it just opened and no item came out, maybe because my first interact in that game was with a drone. Other interactables that would drop an item, like lunar pods, were affected as well, unsurprisingly, not just chests.
### To Reproduce
1. Install ClassicItems along with its dependencies in r2modman
       i. ClassicItems v5.0.1
       ii. TILER2 v4.0.2
       iii. HookGenPatcher v1.2.1
       iv. R2API v3.0.13
       v. BepInExPack v5.4.9
2. Start a modded game
3. Look in the logbook in the menu for Item & Equipment
4. See **"missing items list" error**
5. Start a singleplayer game on Drizzle, with Commando, with Command Artifact enabled
6. See **"no chests" error**
7. Start a singleplayer game again but with Sacrifice Artifact enabled
8. Exit to main menu
9. Start a singleplayer game on Drizzle, with Commando, with Command Artifact enabled and Sacrifice Artifact now disabled
10. Find and open a chest
11. See **"no items" error**

### Expected Behavior
Logbook would be complete with vanilla and modded items, normally would have run with UnlockAll mod to see which specific modded items are there. Before this bug came along, not all items were available for some reason but mod was still functional.

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-ClassicItems/files/6311774/LogOutput.log)

### Additional Context
![FQQn8lR](https://user-images.githubusercontent.com/59487220/114727728-726f5780-9d0c-11eb-9e34-e45bf6709ef7.png)

**Comment by StalwartTirith** [comment] 2021-04-14 22:21
Another interesting thing I noticed was that you could still open up the panel in the pod you spawn in, but it's empty. It still shows the prompt "Press E to take" but the name is gone and pressing the button to take to fuel rod (or whatever that item was) doesn't do anything.

**Comment by StalwartTirith** [comment] 2021-04-14 23:33
Seems like pretty much all item mods are broken. I'm having trouble finding any that don't have the same issue.

**Comment by simonfruehauf** [comment] 2021-04-15 14:05
Having the same issue, it's gotta be an error in the dependencies i guess?

**Comment by cheeeeeeeeeen** [comment] 2021-04-15 15:51
It's R2API. Need to wait for a fix.

**Comment by ThinkInvis** [comment] 2021-04-22 18:57
Almost certainly a duplicate of #86. See comment on said issue; feel free to reopen if it's still happening after I update.

**Closed as completed by ThinkInvis** 2021-04-22 18:57 UTC
Labels: duplicate
